### ISSUE TITLE
Grey page

### ISSUE THREAD

**Issue by Redwards5** [danxfisher/MeetEasier#2]
Hello, 

When browsing to http://localhost:8080 the page loads for a second and in the list I can see all our offices but then the page quickly clears and I'm left with just a grey blank page.

I noticed I keep getting the below error as well.

![image](https://user-images.githubusercontent.com/33692620/32840866-c84dcf42-ca10-11e7-9226-de5e1fc584ac.png)

Any suggestions?

Cheers,
Ryan

**Comment by danxfisher** [comment]
This typically is a response when the account you're using as the service account (account in `config/auth.js`) does not have full permissions to the calendar of the room/mailbox.
    
See: https://stackoverflow.com/questions/29517641/ews-api-2013-calendar-the-specified-folder-could-not-be-found-in-the-store or https://social.msdn.microsoft.com/Forums/exchange/en-US/ef3baa27-d3cc-45c4-87be-c70e59663b33/ews-what-things-could-cause-the-error-the-specified-folder-could-not-be-found-in-the-store?forum=exchangesvrdevelopment
    
Let me know if that helps.

**Comment by Redwards5** [comment]
Hello,

Thanks, I now no longer see those error messages. However, the screen still only displays for a second and then disappears showing a grey page, I've tried IE and firefox. Would you have any more suggestions?

![image](https://user-images.githubusercontent.com/33692620/32896305-99ce043c-cada-11e7-868d-d755fbe99590.png)

I'll admit I'm a sys admin and a bit of a noob with this.

Thanks again for your help!

Cheers,
Ryan

**Comment by danxfisher** [comment]
Are all of the mailboxes located in the cloud?  Also, could you hit F12 in the browser window and post the "Console" section of the browser log?  Thanks.

**Comment by Redwards5** [comment]
Hello, yes all the mailboxes are in the cloud.

Here is the Console browser log:


DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
localhost:8080
HTML1300: Navigation occurred.
localhost:8080
socket connect at: http://localhost:8080
=====================================
TypeError: Unable to get property 'map' of undefined or null reference
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: {
            [functions]: ,
            __proto__: { },
            message: "",
            name: "Error"
         },
         message: "",
         name: "TypeError"
      },
      description: "Unable to get property 'map' of undefined or null reference",
      message: "Unable to get property 'map' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'map' of undefined or null reference
   at value (http://localhost:8080/static/js/main.22b2ee12.js:1:196448)
   at c (http://localhost:8080/static/js/main.22b2ee12.js:1:98761)
   at beginWork (http://localhost:8080/static/js/main.22b2ee12.js:1:100390)
   at o (http://localhost:8080/static/js/main.22b2ee12.js:1:112605)
   at a (http://localhost:8080/static/js/main.22b2ee12.js:1:112929)
   at s (http://localhost:8080/static/js/main.22b2ee12.js:1:113169)
   at w (http://localhost:8080/static/js/main.22b2ee12.js:1:116500)
   at b (http://localhost:8080/static/js/main.22b2ee12.js:1:116238)
   at h (http://localhost:8080/static/js/main.22b2ee12.js:1:115477)
   at d (http://localhost:8080/static/js/main.22b2ee12.js:1:114877)"
   }

Possible Unhandled Promise Rejection (id: 0):
  TypeError: Unable to get property 'map' of undefined or null reference
     at value (http://localhost:8080/static/js/main.22b2ee12.js:1:196448)
     at c (http://localhost:8080/static/js/main.22b2ee12.js:1:98761)
     at beginWork (http://localhost:8080/static/js/main.22b2ee12.js:1:100390)
     at o (http://localhost:8080/static/js/main.22b2ee12.js:1:112605)
     at a (http://localhost:8080/static/js/main.22b2ee12.js:1:112929)
     at s (http://localhost:8080/static/js/main.22b2ee12.js:1:113169)
     at w (http://localhost:8080/static/js/main.22b2ee12.js:1:116500)
     at b (http://localhost:8080/static/js/main.22b2ee12.js:1:116238)
     at h (http://localhost:8080/static/js/main.22b2ee12.js:1:115477)
     at d (http://localhost:8080/static/js/main.22b2ee12.js:1:114877)


Thanks again
Ryan

**Comment by danxfisher** [comment]
So the three main things I would check are:

- The service account you put in the `auth.js` file must have full access to all room mailboxes
- The service account must also be an account/mailbox on Exchange online
- The roomlists must be in Exchange online (cloud)
    
The page will also not load if any rooms/roomlists on the same domain are *not* in Exchange online.  Check those things first.  Thanks.  I will try and update the code with a check to see if anything errors, and skip it.

**Comment by DaniESLUG** [comment]
I had the same issue, and it started to work after create an event in all rooms.
After it I removed/canceled the event and now works perfect

**Comment by Redwards5** [comment]
Hello @danxfisher 
The service account has full access to all room mailboxes, I used a PowerShell script to do this and randomly checked a few to ensure it worked.
The service account is a "normal" user account as such with an account and mailbox in Office 365.
The roomlists as well as the rooms are all Exchange Online.

Since we have multiple domains a few of the rooms use a different domain name, however I don't need to see these rooms so wanted to add them to the ignore list. If my domain is MYPROPERDOMAIN.com and the rooms I want to ignore are WIERDDOMAIN.com is this the correct setup?

auth.js config for username is ServiceAccount@MYPROPERDOMAIN.com and domain is MYPROPERDOMAIN.com

flightboard.config.js config is:

module.exports = {
  'board' : {
    'roomsToSkip' : [
      'DoNotCareAboutThisRoom@WIERDDOMAIN.com',
      'DoNotCareAboutThisRoomEither@WIERDDOMAIN.com',
    ],

Cheers,
Ryan

**Comment by danxfisher** [comment]
@Redwards5 This unfortunately won't skip them while searching via EWS, it only hides them in the front end.  I will work on a multi-domain fix in the next week.

**Comment by Redwards5** [comment]
@danxfisher excellent, thank you so much!

**Comment by am-jo-zt** [comment]
@Redwards5 Pull request #12 should show you the page, even when this error occurs (rooms with errors will be marked with `Error` and the message as tooltip)

**Comment by Redwards5** [comment]
@danxfisher @am-jo-zt will the changes to pull request #12 be submitted to the overall source code? again, i'm new to this so not sure how to get the changes from pull request 12 into the code I've already originally downloaded. Thanks again for your help and patience!
