### ISSUE TITLE
Issue installing on a Pi

### ISSUE THREAD

**Issue by TerrorSource** [danxfisher/MeetEasier#56]
Does anyone have a fix for this?

```
pi@raspberrypi:~/MeetEasier $ sudo "/usr/bin/node" "/usr/bin/npm" "install"
(node:23170) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json meet-easier@ No repository field.
npm WARN package.json meet-easier@ No license field.
npm ERR! Error: Invalid Package: expected types/moment-timezone but found @types/moment-timezone
npm ERR!     at /usr/share/npm/lib/cache/add-local-tarball.js:161:14
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:131:7)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.98-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/MeetEasier
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/MeetEasier/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi:~/MeetEasier $ 
```

**Comment by TerrorSource** [comment]
Issue solved by updating nodejs and npm.
